### ISSUE TITLE
JASIST Paper

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/campaign-access-eval#34]
Overleaf draft: https://www.overleaf.com/project/61f9910b0b519759f8b1feb2 
Google Doc with intro drafting: https://docs.google.com/document/d/1UOLqXhzj_HBOOnfwYCP9qA7mukpE13kwika9q9MOV1E/edit

**Comment by JacksonMaxfield** [comment]
I think wrong overleaf link... You mean for this to be the campaign access eval paper right?
